version: '3.8'
services:
  omop-translator-openai:
    build: .
    environment:
      - LLM_PROVIDER=openai
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "3000:3000"
    
  omop-translator-claude:
    build: .
    environment:
      - LLM_PROVIDER=anthropic
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "3001:3000"